spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database: postgresql
    open-in-view: true
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://daily-steady-db.clgq6c3hfkhr.ap-southeast-2.rds.amazonaws.com:5432/dev
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always

logging:
  pattern:
    console: "\"[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n\""
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
    retepmil.personal.dailysteady: debug

jwt:
  secret: d8e3b829ff785f3465143d93993a36790d569231e969b0aa70a01b437fb7c844