spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        highlight_sql: true
    database: postgresql
    open-in-view: true
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 9000